// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/api/_middleware.ts";
import * as $4 from "./routes/api/x.ts";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/list.tsx";
import * as $7 from "./routes/my-reads.tsx";
import * as $8 from "./routes/read/[slug].tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/api/_middleware.ts": $3,
    "./routes/api/x.ts": $4,
    "./routes/index.tsx": $5,
    "./routes/list.tsx": $6,
    "./routes/my-reads.tsx": $7,
    "./routes/read/[slug].tsx": $8,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
